### ISSUE TITLE
Could not resolve 'deb.oxygene.sk'

### ISSUE THREAD

**Issue by PeterCodar** [acoustid/acoustid-server#35]
Executing `sudo apt-get update`
results in this error:

> Err:1 http://deb.oxygene.sk/ubuntu yakkety InRelease
>   Could not resolve 'deb.oxygene.sk'

(Yes, I have executed `echo "deb http://deb.oxygene.sk/ubuntu lsb_release -c -s main" | sudo tee /etc/apt/sources.list.d/oxygene.list` before)

**Comment by lalinsky** [comment]
I'm sorry, I no longer have the repository available. You can build the PostgreSQL modules from sources for now:

https://github.com/acoustid/pg_acoustid

**Comment by PeterCodar** [comment]
Thank you for the very fast response.
`sudo apt-get install `postgresql-server-dev-9.1` isnt' available anymore.
Can we use 
`sudo apt-get install postgresql-server-dev-9.5 `
instead?

**Comment by lalinsky** [comment]
Yes, you can. It should match the version of PostgreSQL you are running.

**Comment by lalinsky** [comment]
Sorry, I'm not longer going to support the repository.
