### ISSUE TITLE
Missing 'requirements.txt' in pip install

### ISSUE THREAD

**Issue by PeterCodar** [acoustid/acoustid-server#36]
Executing
(e) acoustid@ubuntu:~$ `pip install -r requirements.txt`
results in this error:
`Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`

Where can we get this missing file?

**Comment by lalinsky** [comment]
You are running this from the wrong directory.

**Comment by PeterCodar** [comment]
I just try to follow your 
https://github.com/acoustid/acoustid-server/blob/master/README.md
.-)

**Comment by lalinsky** [comment]
Btw, may I ask for the reason you are installing acoustid-server? I'm asking because unless you want to do some development on the server, I think you are going to be disappointed.

**Comment by PeterCodar** [comment]
Sure.
I try to get a local running copy of your acoustid-server for some test with a new developed fingerprinting client. I don't want to be banned from your official server because of mistakes in my code.

**Comment by lalinsky** [comment]
I really wouldn't do this if it's just that. It's going to be hard and it will not work well in the end. The code was never meant to be running anywhere but on acoustid.org. You might get it working, but you really need to know what you are doing. And in that case, you should just use the included `Vagrantfile` which will setup most things for you.

However, unless you are doing something very special, you are better off using acoustid.org.

**Comment by PeterCodar** [comment]
Thank you for that hints!
Maybe it is really better to try to official acoustid.org.

I hope that I don't have to bother you with 'unbanning' my ip or account in some days.
.-)

**Comment by lalinsky** [comment]
Well, if you are going to do something crazy that might result in that, please let me know in advance. :)

**Comment by PeterCodar** [comment]
I have absolutely no malicious intent. Really.

**Comment by lalinsky** [comment]
Nothing to worry about then. :)

I'll close this issue.
