### ISSUE TITLE
Numeric value out of range

### ISSUE THREAD

**Issue by benjamin-dancecloud** [acoustid/acoustid-server#44]
I am unsure if this is the correct repository to post this question.

I've setup a postgresql server with the fingerprint table from your scripts containing the integer[] column. When I try inserting the raw fingerprints from fpcalc, I get the error 

` Numeric value out of range: 7 ERROR:  value "3464512762" is out of range for type integer`

Am I using fpcalc wrong or is the database wrong?

**Comment by lalinsky** [comment]
Are you writing to the database directly? If so, you need to convert the unsigned 32-bit integer to signed ones.
