### ISSUE TITLE
Google OAuth fails with error 401 on acoustid.org

### ISSUE THREAD

**Issue by nathanielcwm** [acoustid/acoustid-server#64]
![image](https://user-images.githubusercontent.com/22572406/123793104-ef759a80-d913-11eb-9ff9-566f881cec64.png)

**Comment by garlontas** [comment]
Hello,
I have the same problem:
![Error 401:invalid_client](https://user-images.githubusercontent.com/70283087/129354784-e4f4dd19-1bb8-4590-a058-b66c810f6710.png)
