### ISSUE TITLE
Not possible to download  https://data.acoustid.org/fingerprint.delta.2019-11.csv.gz

### ISSUE THREAD

**Issue by ijabz** [acoustid/acoustid-server#76]
Not possible to download  https://data.acoustid.org/fingerprint.delta.2019-11.csv.gz

All other files can be downloaded if we set --tries 0 to allow retries but this file get stuck on byte 283352855 and never gets any further

+ wget --timeout 0 --tries 0 https://data.acoustid.org/fingerprint.delta.2019-11.csv.gz
--2021-10-01 15:27:31--  https://data.acoustid.org/fingerprint.delta.2019-11.csv.gz
Resolving data.acoustid.org (data.acoustid.org)... 104.26.1.251, 104.26.0.251, 172.67.75.70, ...
Connecting to data.acoustid.org (data.acoustid.org)|104.26.1.251|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 494621840 (472M) [application/x-gzip]
Saving to: ‘fingerprint.delta.2019-11.csv.gz’

fingerprint.delta.2019-11.csv.gz                          57%[========================================================================>                                                        ] 270.23M  18.1MB/s    in 16s

2021-10-01 15:27:48 (17.1 MB/s) - Connection closed at byte 283352855. Retrying.

--2021-10-01 15:27:49--  (try: 2)  https://data.acoustid.org/fingerprint.delta.2019-11.csv.gz
Connecting to data.acoustid.org (data.acoustid.org)|104.26.1.251|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 494621840 (472M), 211268985 (201M) remaining [application/x-gzip]
Saving to: ‘fingerprint.delta.2019-11.csv.gz’

fingerprint.delta.2019-11.csv.gz                          57%[+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++                                                        ] 270.23M  --.-KB/s    in 0s

2021-10-01 15:28:05 (0.00 B/s) - Connection closed at byte 283352855. Retrying.

**Comment by autarch** [comment]
I saw the same issue. I was able to eventually download larger files with `wget`, which automatically retried until it was done.
